name: animal_farm
description: Animal Farm

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0
  flare_flutter: ^1.7.3
  simple_animations : ^1.3.4
  slimy_card: ^1.0.1
  geopattern_flutter: ^0.1.1
  percent_indicator: ^2.1.1
  crypto: ^2.1.3
  frideos: ^0.6.0
  avatar_glow: ^1.0.0
  animated_text_kit: ^1.3.1
  clock:  ^1.0.1
  bubble: ^1.1.9
  photo_view: ^0.7.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  sticky_headers: ^0.1.8
  shared_preferences: ^0.5.3
  flutter_ringtone_player: ^1.0.3
dev_dependencies:
  flutter_native_splash: ^0.1.9
  flutter_launcher_icons: ^0.7.3
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon-710x599.png"

flutter_native_splash:
  image: assets/images/splash.png
  color: "42a5f5"
  fill: false

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/post/
     - assets/images/badge/
     - assets/images/avatar/
     - assets/images/location/
     - assets/images/
     - assets/icon/
     - assets/questions.json
     - assets/messages.json
  fonts:
    - family: SpecialElite
      fonts:
        - asset: fonts/Special_Elite/SpecialElite-Regular.ttf
    - family: Raleway
      fonts:
        - asset: fonts/Raleway/Raleway-Regular.ttf
        - asset: fonts/Raleway/Raleway-Italic.ttf
          style: italic
    - family: Alatsi
      fonts:
            - asset: fonts/Alatsi/Alatsi-Regular.ttf

    - family: PermanentMarker
      fonts:
        - asset: fonts/PermanentMarker/PermanentMarker-Regular.ttf
